use `customer-shopping-behaviour`;
-- Q.1: what is the total revenue generated by male vs female customers?
select gender,sum(purchased_amount) as total_revenue
from customer
group by gender; 

-- Q.2: Which customer used a discount but still spent more than the average purchased amount?
select customer_id,purchased_amount
from customer 
where discount_applied="Yes" and purchased_amount>(select avg(purchased_amount) from customer);

-- Q.3: which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as average_product_rating
from customer
group by item_purchased 
order by average_product_rating desc
limit 5;

-- Q.4: compare the average purchase amount between standard and express shipping?
select shipping_type, round(avg(purchased_amount),2) as average_purchased_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q.5:Do subscribed customers spend more compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status, count(customer_id) as total_customers, 
round(avg(purchased_amount),2) as avg_spend,
round(sum(purchased_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q.6 Which 5 products have the highest percent of purchases with discount applied?
SELECT
    item_purchased,
    ROUND(
        100 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*), 2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 

-- Q.7: segment customers into New,Returning and Loyal based on their number of pervious purchases and show the count of each segment?
with customer_type as (select customer_id, previous_purchases,
case 
	when previous_purchases=1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
    end as customer_segment 
from customer)
select customer_segment, count(*) as "Number_of_customer"
from customer_type
group by customer_segment;

-- Q.8: What are the top 3 most purchased product within each category?
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 3;

-- Q.9: Are customers who are repeat buyers more than 5 previous purchases also likely to subscribe?
select subscription_status,
count(customer_id) as repeated_buyers 
from customer
where previous_purchases>5 
group by subscription_status;

-- Q.10: what is the revenue contribution of each age group?
select age_group, sum(purchased_amount) as total_revenue
from customer 
group by age_group 
order by total_revenue desc;